solution:
  board_name: cb5864
  ld_script: ""
type: solution
name: smart_voice_fan_demo
version: v7.3.0                                     # <必选项> 组件版本号
description: 智能语音风扇例程
keywords:
  - sc5864
  - cb5864
  - solution
author: feimi
license: Apache license v2.0
depends:
  - cb5864: V7.3.0
  - csi_sc5864: V7.3.0
  - csi: V7.3.0
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 512
  CONFIG_BOARD_NAME: cb5864
  CONFIG_CHIP_NAME: sc5864
  CONFIG_CHIP_SC5654A: 1
  CONFIG_CLI: 1
  CONFIG_CPU: ck803ef
  CONFIG_CPU_CK803EF: 1
  CONFIG_LOG_LEVEL_DEFAULT: 3
  CONFIG_DEBUG: 1
  CONFIG_KERNEL_NONE: y
  CONFIG_NON_ADDRESS_FLASH: 1
  CONFIG_NUTTXMM_NONE: 1
  CONFIG_PARAM_NOT_CHECK: 1
  CONFIG_SOFTWDT: 1
  CONFIG_STARTUP_MODE_LONG: y
  CONFIG_SYSTICK_HZ: 1000
  CONFIG_VENDOR_NAME: silan
build_config:
  internal_include:
    - ""
  include:
    - include
    - app/include
  cflag: -Os  -g  -Wall  -ffunction-sections -fdata-sections -mhard-float  -Wl,-zmax-page-size=1024 -Wno-address -Wno-unused-but-set-variable -Wno-main -Wno-unused-function -mno-required-printf
  cxxflag: -Os  -g  -Wall  -ffunction-sections -fdata-sections -mhard-float  -Wl,-zmax-page-size=1024 -Wno-address -Wno-unused-but-set-variable -Wno-main -Wno-unused-function
  asmflag: ""
  ldflag: -Wl,-zmax-page-size=1024 -mhard-float  -Wl,-ckmap="yoc.map"
  define:
    - ""
  libs:
    - m
  libpath:
    - ""
source_file:
  - app/src/*.c
link_config:
  path: ~
  library: ~
hidden: false
homepage: https://occ.t-head.cn
