
## 第一部分： 基础信息
name: yocopen                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.3.0                                     # <必选项> 组件版本号
description: 开源 yoc  # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  # base component
  - csi: V7.3.0
  - minilibc: V7.3.0
  - aos: V7.3.0
  - console: V7.3.0
  - drivers: V7.3.0
  - kv: V7.3.0
  - rhino: V7.3.0
  - posix: V7.3.0

  # network
  - lwip: V7.3.0
  - sal: V7.3.0
  - coap: V7.3.0
  - sntp: V7.3.0
  - netmgr: V7.3.0
  - httpclient: V7.3.0
  - transport: V7.3.0
  - webclient: V7.3.0
  - ntp: V7.3.0
  - fota: V7.3.0
  - websocket: V7.3.0
  - mbedtls: V7.3.0
  - wifi_provisioning: V7.3.0

  # media
  - aui_cloud: V7.3.0
  - aui_demo: V7.3.0
  - ipc: V7.3.0
  - mic: V7.3.0
  - minialsa: V7.3.0
  - pvmp3dec: V7.3.0
  - record: V7.3.0
  - voice: V7.3.0
  - av: V7.3.0
  - amrnb: V7.3.0
  - amrwb: V7.3.0
  - av_cp: V7.3.0
  - speexdsp: V7.3.0
  - flac: V7.3.0

  # iot
  - aliot: V7.3.0
  - yunio: V7.3.0

  # fs
  - vfs: V7.3.0
  - fatfs: V7.3.0
  - spiffs: V7.3.0
  - littlefs: V7.3.0

  # security
  - tee: V7.3.0

  # others
  - at: V7.3.0
  - ers: V7.3.0
  - button: V7.3.0
  - adc_button: V7.3.0
  - clock_alarm: V7.3.0
  - ble_mesh: V7.3.0
  - cjson: V7.3.0

  # drivers
  - drv_bt_rtl8723ds: V7.3.0
  - drv_wifi_rtl8723ds: V7.3.0
  - drv_sdmmc: V7.3.0
  - drv_sensors: V7.3.0
  - drv_wifi_esp8266: V7.3.0
  - drv_wifi_m88wi6700s: V7.3.0
  - drv_snd_pangu: V7.3.0
  - drv_sensors: V7.3.0
  - drv_leds: V7.3.0
  - drv_wifi_esp8266: V7.3.0

  # chip
  - csi_pangu: V7.3.0
  - csi_dummy: V7.3.0
  - csi_ch2201: V7.3.0

  # boards
  - board_dummy: V7.3.0
  - pangu_cpu0: V7.3.0
  - cb2201: V7.3.0

  # demo soution
  - helloworld: V7.3.0
  - pangu_player: V7.3.0
  - pangu_tee: V7.3.0
  - pangu_tee_test: V7.3.0
  - alicoap_demo: V7.3.0
  - alimqtt_sensor_data_to_cloud_demo: V7.3.0
