solution:
  board_name: cb2201
  ld_script: ""
type: solution
name: led_blink_demo
yoc_version: 7.2
description: 基于cb2201的LED电灯示例
keywords:
  - cb2201
  - solution
author: feimi
license: Apache license v2.0
depends:
  - aos: V7.2.2
  - cb2201: V7.2.2
  - csi_ch2201: V7.2.2
  - console: V7.2.2
  - csi: V7.2.2
  - drivers: V7.2.2
  - minilibc: V7.2.2
  - rhino: V7.2.2
  - kv: V7.2.2
defconfig:
  CONFIG_ARCH_CSKY: 1
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_BOARD_NAME: cb2201
  CONFIG_CHIP_CH2201: 1
  CONFIG_CHIP_NAME: ch2201
  CONFIG_CLI: 1
  CONFIG_CLOUDIO_ALIMQTT: 1
  CONFIG_CPU: ck802
  CONFIG_CPU_CK802: 1
  CONFIG_DEBUG: 1
  CONFIG_KERNEL_RHINO: 1
  CONFIG_TEE_CA: 1
  CONFIG_VENDOR_NAME: csky
build_config:
  internal_include:
    - ""
  include:
    - app/include
    - app/src
    - include
  cflag: -Og  -g  -Wall  -ffunction-sections -fdata-sections -Wno-address -Wno-unused-but-set-variable -Wno-main
  cxxflag: -Og  -g  -Wall  -ffunction-sections -fdata-sections -Wno-address -Wno-unused-but-set-variable -Wno-main
  asmflag: "  "
  ldflag: -Wl,-zmax-page-size=1024
  define:
    - ""
  libs:
    - m
  libpath:
    - ""
source_file:
  - app/src/app_main.c
  - app/src/cli_cmd.c
  - app/src/init.c
link_config:
  path: ~
  library: ~
hidden: false
homepage: https://occ.t-head.cn
