name: pangu_demo
version: v7.3.0                                     # <必选项> 组件版本号
description: 盘古语音demo方案

type: solution

solution:
  board_name: pangu_cpu0
  cpu_id: cpu0
  ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - csi: V7.3.0
  - rhino: V7.3.0
  - minilibc: V7.3.0
  - aos: V7.3.0
  - console: V7.3.0
  - csi_pangu: V7.3.0
  - netmgr: V7.3.0
  - drivers: V7.3.0
  - drv_wifi_rtl8723ds: V7.3.0
  - drv_sdmmc: V7.3.0
  - drv_snd_pangu: V7.3.0
  - pangu_cpu0: V7.3.0 # '>' | ‘>=' | ''
  - minialsa: V7.3.0
  - ipc: V7.3.0
  - posix: V7.3.0
  - ntp: V7.3.0
  - fota: V7.3.0
  - lwip: V7.3.0
  - aui_cloud: V7.3.0
  - aui_demo: V7.3.0
  - voice: V7.3.0
  - record: V7.3.0
  - webclient: V7.3.0
  - websocket: V7.3.0
  - mic: V7.3.0
  - av: V7.3.0
  - kv: V7.3.0
  - cjson: V7.3.0
  - button: V7.3.0
  - mbedtls: V7.3.0
  - vfs: V7.3.0
  # - bt: V7.3.0
  - ble_mesh: V7.3.0
  - drv_bt_rtl8723ds: V7.3.0
  - fatfs: V7.3.0
  - httpclient: V7.3.0

# 编译参数
build_config:
  include:
    - app/include
    - app/src
    - app/src/audio
    - app/src/wifipair
    - app/src/wifipair/ap
  libs:
    - SonaAef_c
    - resample
    - m
  libpath:

  cflag: -O2 -Wall
  cxxflag: -O2  -Wall
  asmflag: ""

  ldflag:


# 源文件
source_file:
  - app/src/init/cli_cmd.c
  - app/src/init/init.c
  - app/src/cmd_proc_music_url.c
  - app/src/cmd_proc_xunfei_music.c
  - app/src/cmd_proc_xunfei_tts.c
  - app/src/cmd_proc_xunfei_cmd.c
  - app/src/cmd_proc_text_cmd.c
  - app/src/nlp_json_parse.c
  - app/src/cli_auitalk.c
  - app/src/cmd_proc_xf_asr.c
  - app/src/cmd_proc_aliyun_rasr.c
  - app/src/cmd_proc_xunfei_story.c
  - app/src/app_player.c
  - app/src/app_net.c
  - app/src/wifipair/pair_broadcast.c
  - app/src/app_rtc.c
  - app/src/app_main.c
  - app/src/cop_fota.c
  - app/src/app_lpm.c
  - app/src/app_button.c
  - app/src/app_led.c
  - app/src/app_led_demo.c
  - app/src/iperf.c
  - app/src/cli_apps.c
  - app/src/audio/audio_res.c
  - app/src/audio/net_fail.mp3.c
  - app/src/audio/net_succ.mp3.c
  - app/src/audio/sorry.mp3.c
  - app/src/audio/sorry2.mp3.c
  - app/src/audio/starting.mp3.c
  - app/src/audio/hello.mp3.c
  - app/src/audio/ok.mp3.c
  - app/src/audio/net_cfg_conn.mp3.c
  - app/src/audio/net_cfg_start.mp3.c
  - app/src/audio/net_cfg_switch.mp3.c
  - app/src/audio/net_cfg_config.mp3.c
  - app/src/audio/net_cfg_fail.mp3.c
  - app/src/audio/net_cfg_timeout.mp3.c
  - app/src/audio/play_err.mp3.c
  - app/src/wifipair/ap/ap_pair.c
  - app/src/a2dp/a2dp.c ? <CONFIG_USING_BT_CMP>
  - app/src/a2dp/bt_app_av.c ? <CONFIG_USING_BT_CMP>
  - app/src/a2dp/bt_app_core.c ? <CONFIG_USING_BT_CMP>


def_config:
  CONFIG_DEBUG: 1
  # CONFIG_DEBUG_MM: 1
  CONFIG_ARCH_CSKY: 1
  CONFIG_PARAM_NOT_CHECK: 1

  CONFIG_CLI: 1
  CONFIG_NETMGR_WIFI: 1

  CONFIG_KV_SMART: 1
  CONFIG_AT: 1
  CONFIG_NTP: 1
  CONFIG_USING_TLS: 1

  CONFIG_TCPIP: 1
  CONFIG_WIFI_RTL8723DS: 1

  CONFIG_NON_ADDRESS_FLASH: 1

  CONFIG_SOFTWDT: 1

  CONFIG_TEE_CA: 1
  # CONFIG_SYSTEM_SECURE: 1

  CONFIG_KERNEL_WORKQUEUE: 1
  CONFIG_SYSTICK_HZ: 1000

  CONFIG_HAVE_VIC: 1
  CONFIG_KERNEL_RHINO: 1
  CONFIG_ARCH_INTERRUPTSTACK: 4096

  CONFIG_FFTXER_SPEEX: 0
  CONFIG_FFTXER_IPC: 0
  CONFIG_RESAMPLER_SILAN: 0
  CONFIG_RESAMPLER_SPEEX: 1
  CONFIG_RESAMPLER_IPC: 0
  CONFIG_AEFXER_SONA: 1
  CONFIG_AEFXER_IPC: 0
  CONFIG_DECODER_PCM: 1
  CONFIG_DECODER_PVMP3: 0
  CONFIG_DECODER_FLAC: 1
  CONFIG_DECODER_ADPCM_MS: 1
  CONFIG_DECODER_AMRNB: 1
  CONFIG_DECODER_AMRWB: 1
  CONFIG_DECODER_IPC: 1

  # CONFIG_LED_TASK_ON: 1
  CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN: 16384
  ## for ble_mesh compoennt
  CONFIG_BLE_MESH_PROV: 1
  CONFIG_VENDOR_NAME: csky


