name: pangu_demo
version: v7.2-dev
description: YoC YunVoice SDK

type: solution
yoc_version: V7.2.2

solution:
  board_name: pangu_cpu0
  cpu_id: cpu0
  ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - csi: V7.2.2
  - rhino: V7.2.2
  - minilibc: V7.2.2
  - aos: V7.2.2
  - console: V7.2.2
  - csi_pangu: V7.2.2
  - netmgr: V7.2.2
  - drivers: V7.2.2
  - drv_wifi_rtl8723ds: V7.2.2
  - drv_sdmmc: V7.2.2
  - drv_snd_pangu: V7.2.2
  - pangu_cpu0: V7.2.2 # '>' | ‘>=' | ''
  - minialsa: V7.2.2
  - ipc: V7.2.2
  - posix: V7.2.2
  - ntp: V7.2.2
  - fota: V7.2.2
  - lwip: V7.2.2
  - aui_cloud: V7.2.2
  - voice: V7.2.2
  - record: V7.2.2
  - webclient: V7.2.2
  - websocket: V7.2.2
  - mic: V7.2.2
  - av: V7.2.2
  - kv: V7.2.2
  - cjson: V7.2.2
  - button: V7.2.2
  - mbedtls: V7.2.2
  - vfs: V7.2.2
  - aos: V7.2.2
  - bt: V7.2.2
  - drv_bt_rtl8723ds: V7.2.2
  - fatfs: V7.2.2
  - httpclient: V7.2.2

# 编译参数
build_config:
  include:
    - app/include
    - app/src
    - app/src/audio
    - app/src/wifipair
    - app/src/wifipair/ap
    - include
  libs:
    - SonaAef_c
    - resample
  libpath:

  cflag: -O2 -Wall
  cxxflag: -O2  -Wall
  asmflag: ""

  ldflag:


# 源文件
source_file:
  - app/src/init/cli_cmd.c
  - app/src/init/init.c
  - app/src/cmd_proc_baidu_asr.c
  - app/src/cmd_proc_music_url.c
  - app/src/cmd_proc_xunfei_music.c
  - app/src/cmd_proc_xunfei_tts.c
  - app/src/cmd_proc_xunfei_cmd.c
  - app/src/cmd_proc_text_cmd.c
  - app/src/nlp_json_parse.c
  - app/src/cli_auitalk.c
  - app/src/cmd_proc_xf_asr.c
  - app/src/cmd_proc_proxy_ws_asr.c
  - app/src/cmd_proc_aliyun_rasr.c
  - app/src/cmd_proc_xunfei_story.c
  - app/src/app_player.c
  - app/src/app_net.c
  - app/src/wifipair/pair_broadcast.c
  - app/src/app_rtc.c
  - app/src/app_main.c
  - app/src/cop_fota.c
  - app/src/app_button.c
  - app/src/app_led.c
  - app/src/app_led_demo.c
  - app/src/iperf.c
  - app/src/cli_apps.c
  - app/src/audio/audio_res.c
  - app/src/audio/net_fail.mp3.c
  - app/src/audio/net_succ.mp3.c
  - app/src/audio/sorry.mp3.c
  - app/src/audio/sorry2.mp3.c
  - app/src/audio/starting.mp3.c
  - app/src/audio/hello.mp3.c
  - app/src/audio/ok.mp3.c
  - app/src/audio/net_cfg_conn.mp3.c
  - app/src/audio/net_cfg_start.mp3.c
  - app/src/audio/net_cfg_switch.mp3.c
  - app/src/audio/net_cfg_config.mp3.c
  - app/src/audio/net_cfg_fail.mp3.c
  - app/src/audio/net_cfg_timeout.mp3.c
  - app/src/audio/play_err.mp3.c
  - app/src/wifipair/ap/ap_pair.c
  - app/src/a2dp/a2dp.c
  - app/src/a2dp/bt_app_av.c
  - app/src/a2dp/bt_app_core.c


defconfig:
  CONFIG_DEBUG: 1
  # CONFIG_DEBUG_MM: 1
  CONFIG_ARCH_CSKY: 1
  CONFIG_PARAM_NOT_CHECK: 1

  CONFIG_CLI: 1
  CONFIG_NETMGR_WIFI: 1

  CONFIG_KV_SMART: 1
  CONFIG_AT: 1
  CONFIG_NTP: 1
  CONFIG_USING_TLS: 1

  CONFIG_TCPIP: 1
  CONFIG_WIFI_RTL8723DS: 1

  CONFIG_NON_ADDRESS_FLASH: 1

  CONFIG_SOFTWDT: 1

  # CONFIG_TEE_CA: 1

  CONFIG_KERNEL_WORKQUEUE: 1
  CONFIG_SYSTICK_HZ: 1000

  CONFIG_CPU_CK804EF: 1
  CONFIG_CHIP_VENDOR_CSKY: 1
  CONFIG_CHIP_PANGU: 1
  CONFIG_CHIP_PANGU_CPU0: 1
  CONFIG_HAVE_VIC: 1
  CONFIG_KERNEL_RHINO: 1
  CONFIG_ARCH_INTERRUPTSTACK: 4096

  CONFIG_FFTXER_SPEEX: 0
  CONFIG_FFTXER_IPC: 0
  CONFIG_RESAMPLER_SILAN: 1
  CONFIG_RESAMPLER_SPEEX: 0
  CONFIG_RESAMPLER_IPC: 0
  CONFIG_AEFXER_SONA: 1
  CONFIG_AEFXER_IPC: 0
  CONFIG_DECODER_PCM: 1
  CONFIG_DECODER_PVMP3: 0
  CONFIG_DECODER_FLAC: 1
  CONFIG_DECODER_ADPCM_MS: 1
  CONFIG_DECODER_AMRNB: 1
  CONFIG_DECODER_AMRWB: 1
  CONFIG_DECODER_IPC: 1

  CONFIG_SYSTEM_SECURE: 1
  CONFIG_VENDOR_NAME: "csky"
  CONFIG_CHIP_NAME: "pangu"
  CONFIG_BOARD_NAME: "pangu_cpu0"
  CONFIG_CPU: "ck804ef"

  # CONFIG_LED_TASK_ON: 1


