name: helloworld
version: v7.3.0                                     # <必选项> 组件版本号
description: YoC helloworld SDK

type: solution

solution:
  cpu_id: cpu0
  board_name: pangu_cpu0
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: csky
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld.S

depends:                                       # 该组件依赖其他的组件
  - csi: V7.3.0
  - rhino: V7.3.0
  - minilibc: V7.3.0
  - aos: V7.3.0
  - console: V7.3.0
  - drivers: V7.3.0
  # board components
  - board_dummy: V7.3.0
  - pangu_cpu0: V7.3.0
  - cb2201: V7.3.0
  - cb5654: V7.3.0


# 编译参数
build_config:
  include:
    - app/include

  ldflag: -Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024

# 源文件
source_file:
  - app/src/init/cli_cmd.c
  - app/src/init/init.c
  - app/src/main.c

def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_CLI: 1
  CONFIG_DEBUG: 1
  CONFIG_KERNEL_RHINO: 1
