name: usrsock
version: v7.3.0                                     # <必选项> 组件版本号
description: User Socket Adapter Layer
tag: 核心模块
keywords:
  - base

license: Apache license v2.0              # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

homepage: ""

type: common

depends:                                  # 该组件依赖其他的组件
  - csi: V7.3.0
  - rhino: V7.3.0
  - vfs: V7.3.0
  - posix: V7.3.0
  - aos: V7.3.0

source_file:
  -  'devif_callback.c'
  -  'usrsock_conn.c'
  -  'usrsock_dev.c'
  -  'usrsock_ops.c'
  -  'usrsock_helper.c'
  -  'ip4_addr.c'
  -  'def.c'
  -  'ping.c'
  -  'ping_v4.c'

build_config:
  include:
    - include
  cflag: '-Wno-pointer-arith'             # C 编译器所需要要的编译参数
  # define:                               # 宏定义

install:
  - dest: include
    source:
      - "include/*.h"
